### ISSUE TITLE
About new feature 

### ISSUE THREAD

**Issue by masayil** [bnb-chain/bsc#1026]
1)If I dont't want to enable new feature #926 . Do I need to make any changes？
This is my command:`geth_linux --cache 64000 --datadir /root/svc/node --config /root/svc/config.toml --pipecommit --txlookuplimit 0 --rpc.txfeecap 0 --txpool.reannouncetime 5m --syncmode full`
2) conflict with the nodes enabled archive mode？

**Comment by guagualvcha** [comment]
1) No, no need to change anything.
2) If you are running an archive node, you should not enable fastnode.

**Comment by kugimiya530** [comment]
> 1. No, no need to change anything.
> 2. If you are running an archive node, you should not enable fastnode.

Hi if we are running fullnode with v1.1.11 with --diffetent

For us , v1.1.12 new feature fastnode better or original fullnode ,which one is better performance

**Comment by forcodedancing** [comment]
@kugimiya530 You can try fastnode, which has the better performance.

It turns out that the fast node can slow down the storage growth by 60%~90% according to different settings and increase the syncing efficiency by about 30%. We encourage node operators who do not care about 100% state consistency to enable fast nodes by appending --tries-verify-mode none to the node command. https://github.com/bnb-chain/bsc/releases
