### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by a04512** [bnb-chain/bsc#1115]
If you can block an address, why don't you add several stablecoins on the chain the blacklist function. I was stolen $800,000 a few days ago with.If this function is available, the funds may still be saved（he still didn't move the funds stolen from my account now）.
@guagualvcha

**Comment by dgdeivid** [comment]
An onchain lock function on stablecoins can be very dangerous because someone who has legitimately sent tokens can fake a theft and ask for a lock. Those who can call these blocking functions could abuse their power or be forced by politicians to block certain addresses.

In this case, it has been necessary to stop the BSC for several hours to block some addresses. Seems to me a good thing, because that encourages not to do it unless it is extremely necessary.

**Comment by Undead8** [comment]
@a04512 There is a big difference between an on-chain exploit and scams that happen off-chain. How are you going to prove that you were "stolen" and that it was not a legitimate intentional transfer? Obviously you will need a court order that orders the transaction to be reversed. A human with admin privilege will have to review that court order and decide if the transaction should be reversed based on the wording of that particular court order. If the blockchain allows this kind of admin control, it might as well be a CEX.

An on-chain exploit is verifiable on-chain without any external input.
