### ISSUE TITLE
Why this node not packaged according to the  gasprice

### ISSUE THREAD

**Issue by xiaozanooo** [bnb-chain/bsc#1171]
Why this node not packaged according to the  gasprice

https://bscscan.com/txs?block=22899601

**Comment by 0xLyon** [comment]
@xiaozanooo Can you please advise what you mean with "not packaged according to the gasprice"?

**Comment by iGloom** [comment]
He means the validator 0x61dd481a114a2e761c554b641742c973867899d3 (which validated that block) is not respecting gas price, when mining the block. 
For example, txn 0x535154fffd3eb81c1592662096a15c721d8e0cade25ad882137a988b3385792b from that block was mined too late for its gas price (between 2 transactions with gas 5, while txn itself has gas 8+).
I see the same behaviour in other blocks from that validator, and believe the validator should be slashed for this - that's clearly the signs of some block position manipulations happen, also this leads to gas price being useless.

**Comment by kris-ss** [comment]
@iGloom We are checking this with the team. Thanks for the details.

**Comment by brilliant-lx** [comment]
It is recovered right now.
And BNB Chain consensus doesn't promise the GasPriceOrder right now, validators still can pack transactions without obeying the GasPriceOrder rule, so does Ethereum.
Validators try to add transactions with high gas price first, that is because these transactions could give more reward to validators.

There are 2 reasons that we don't want to apply the GasPrice Rule:
1.It will make the TxPool, Reorg logic very complicated to guarantee the GasPrice order, you may refer: https://github.com/bnb-chain/bsc/issues/158
2.Even with gas price order, validator still can reject to pack the high gas price transactions.

However, there does have different opinions, it is welcomed to discuss.
