### ISSUE TITLE
Why the BSC block gas limit change ?

### ISSUE THREAD

**Issue by Thiou21** [bnb-chain/bsc#1242]
The bsc block gas limit is always very close to 140,000,000. But it can vary a little for some blocks.

For exemple, the block 23,934,046 with a gas limit of 140,000,000 : https://bscscan.com/block/23934046
               and the block 23,934,047 with a gas limit of 139,453,126 : https://bscscan.com/block/23934047

Why does it change and what's the logic behind this ? 
Why not just make it constant at 140M ?

**Comment by cosinlink** [comment]
upgrade the geth version to the latest

**Comment by ZiyuanStar** [comment]
gas limit could be specified or configured by transactor or miner, you can find the latest statistics here:
https://bscscan.com/chart/gaslimit

**Comment by Thiou21** [comment]
But even for each validator it's not constant
For exemple block 23,949,426 validated by Defibit have 139,440,359 gas limit : https://bscscan.com/block/23949426
and block 23,949,447 also validated by Defibit have 138,359,445 gas limit : https://bscscan.com/block/23949447

Why a little variation like this ? It seems to make no sense and looks like a bug

**Comment by ZiyuanStar** [comment]
it's total gas limit provided by all tx in that block, no need to be constant

**Comment by Thiou21** [comment]
Not really, it has nothing to do with the sum of gas limits or sum of gas used :

Block 23980081 | Sum gas used 10,752,364 | Sum gas limits 23,685,022 | Block gas limit 138,361,557
Block 23980082 | Sum gas used 12,842,305 | Sum gas limits 41,241,065 | Block gas limit 138,902,030
Block 23980083 | Sum gas used 12,404,499 | Sum gas limits 20,848,219 | Block gas limit 138,359,445
Block 23980084 | Sum gas used 9,161,340 | Sum gas limits 16,668,409 | Block gas limit 138,899,910
Block 23980085 | Sum gas used 10,309,846 | Sum gas limits 27,934,456 | Block gas limit 139,442,486
Block 23980086 | Sum gas used 11,289,915 | Sum gas limits 40,213,435 | Block gas limit 139,987,182
Block 23980087 | Sum gas used 9,895,586 | Sum gas limits 27,559,408 | Block gas limit 140,000,000
Block 23980088 | Sum gas used 12,034,806 | Sum gas limits 40,051,400 | Block gas limit 140,000,000
Block 23980089 | Sum gas used 11,200,620 | Sum gas limits 21,328,645 | Block gas limit 140,000,000
Block 23980090 | Sum gas used 9,662,758 | Sum gas limits 24,368,251 | Block gas limit 140,000,000

It seems to be independant of other factors because it's always between 137M and 140M
Interestingly the ethereum blockchain has a constant block gas limit of 30M

**Comment by clostao** [comment]
Any further discovery in this little variation? 

Such a small variation cannot be provoked by a mechanism like Ethereum's variable block gas limit model or at least in that maintained way.

**Comment by clostao** [comment]
I've been reviewing the source code for the bnb node (erigon version). I've discovered that it follows the same mechanism as Ethereum or Polygon in which in each block, the producer could vary the gas limit by (parent_block_gas_limit / 1024). In Ethereum & Polygon seemed to be introduced in the London fork (not adopted by BNB) but in BNB has been introduced without this fork. 

Nodes have in their configuration a parameter called [TargetGasLimit](https://github.com/bnb-chain/erigon/blob/abb5c9a5c4bd701de5d7fb4fb9b6b0f8f7c167c8/eth/stagedsync/stage_mining_create_block.go#L211) this would make the nodes propose a block with this TargetGasLimit or the closest in the available range (due to the parent_block_gas_limit / 1024 restriction). 

One posible answer is that a BNB node hasn't changed their TargetGasLimit param from 120M to 140M so when this node gets a block mined the produced block gas limit would slighty decrease a bit.

**Comment by owen-reorg** [comment]
According to the protocol, any value between min block gas limit and max block gas limit is valid.
The gas limit on Ethereum was also dynamic before block #14996763. Check <https://etherscan.io/block/14996763> and <https://etherscan.io/block/14996764>.

I guess Ethereum changed the implementation details a little bit and BSC didn't follow.

What's the demand to make it constant here? I thought it was a convention thing, not a bug.

**Comment by Thiou21** [comment]
It's not really a bug but it's useless to have little variations like this.
That's why eth made it constant and I think bsc should do the same

**Comment by Thiou21** [comment]
In practice it moves between 137M and 140M so I don't really see how it can affect perfomance, the variations are too small

**Comment by brilliant-lx** [comment]
GasLimit is dynamically changed to represent the majority validator's Gas capability.
The GasLimit fluctuates, because some validators set its GasLimit below 140M, they try to pull it down, but they are not the majority, so the GasLimit will be pulled up again by other validators which set their GasLimit to 140M.
