### ISSUE TITLE
How to set " Transaction Index " or " Position " in a Block ?

### ISSUE THREAD

**Issue by banlieu451** [bnb-chain/bsc#1282]
Hello everybody, i have my BSC FULL NODE **not a miner node** ...

My geth command is : 
`./geth --config ./config.toml --datadir ./node --cache 18000 --rpc.allow-unprotected-txs --txlookuplimit 0 --maxpeers 60000 --syncmode full --ws --ws.port 8546 --ws.addr localhost console`

How can i **set position in block** ? i mean about Tx position .. Because **this is possible**.

If i send a transaction in a block my Tx as TransactionIndex "null", eg. if i put "1.000 GWEI",  i **understand** i'm gonna be in the top because miner take my Tx fast but we are seaching to know **how to set** the position in a block about our own Tx ?

<img width="320" alt="a" src="https://user-images.githubusercontent.com/76543738/214130520-1ae4224a-fbb0-490f-93bb-c177f0bdc094.png">

In this example : Position is **53** , How to be number **54** for example not **55** not **56** not **75** 

The **step** to change the **GasLimit** appear to be **not enought**

**Need I "bypass" mempool ? 
Need I send my Tx directly to a miner ?
Need i be geth miner and send my own Tx about mempool ?**

Is there any tutorial ?

Sincerely Mike

**Comment by EngineBusd** [comment]
I guess to pay more transaction fees. 
detect the transaction and pay the high fee it would directly frontrun I myself made it one. Since 3 months I am doing this.

**Comment by banlieu451** [comment]
> Je suppose qu'il faut payer plus de frais de transaction. détecter la transaction et payer les frais élevés qu'elle entraînerait directement, j'en ai moi-même fait une. Depuis 3 mois je fais ça.

You mean to pay low gas fees ? I want be in the next position of my Tx next position block ?

You gess ? You are asking ?

**Comment by isaacyuno** [comment]
Txn order in a block is decided by validators. Generally, transactions are sorted by Nonce->GasPrice->ArrivalTime, which means the higher the gas fee you set, the higher chance your txn will be put in the top place in a block.

However, it is not easy to specify the exact place/txn index in a block, I'm saying it is not easy because arbitrage bots are
rack their brains to get this done. 

I would recommend you to read this article. https://medium.com/coinmonks/can-you-earn-a-lambo-by-being-a-flash-arbitrageur-on-bnb-smart-chain-b119701329fe
You could start from here if you don't have time to go through all of it and then I think you would know why I say it is not easy https://medium.com/coinmonks/can-you-earn-a-lambo-by-being-a-flash-arbitrageur-on-bnb-smart-chain-b119701329fe#:~:text=Let%E2%80%99s%20Try%20Arbitrage!

**Comment by banlieu451** [comment]
thanks for answer but its not arbitrage the true i find way to get the position +1 is to manipulate the Gaslimit normally some questions still without response 

can we bypass mempool ln BSC ?

**Comment by CocoStarZ** [comment]
No more follow-up, close it for now
