### ISSUE TITLE
Why do you keep an "don't use" release in master branch ??!!!

### ISSUE THREAD

**Issue by 48ClubIan** [bnb-chain/bsc#1477]
https://github.com/bnb-chain/bsc/releases/tag/v1.1.22
v1.1.22 is released twice ! in two days !
And than the changelog to "Don't use this release!!!" later.

Why not delete this release and send an alert to repo subscriber?

First time:
![image](https://user-images.githubusercontent.com/39881426/232329643-957fe84b-5af7-4e3c-8fa0-848641648717.png)
Second time:
![image](https://user-images.githubusercontent.com/39881426/232329662-74683f17-5edb-48ed-8246-dcd6040ce403.png)

**Comment by brilliant-lx** [comment]
1.re-released it due to the broken docker image
  see: https://github.com/bnb-chain/bsc/issues/1438
2.then we found a critical bug in this release...
  so I added the notice(don't use)and set it to pre-Release
3.We fixed it and publish a new release: v1.1.23 later

Sorry for the trouble, we will avoid it next time. I think we can just delete it in such case.

**Comment by brilliant-lx** [comment]
but simple delete the release would make the version won't continuous,.
It could break someone's script, such as: https://github.com/bnb-chain/bsc/issues/1285

**Comment by kucharskim** [comment]
Just bump the release with new version. Don't re-release the same software with exact same version. Automation already kicked in and already build it on ppl build farms, so what was release should not be un-released as world today is too automated. Just bump the version, with proper fix.
