### ISSUE TITLE
Validators in puissant service skipping off turn block proposals

### ISSUE THREAD

**Issue by Ezkerrox** [bnb-chain/bsc#1489]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

Once any validator skips an inturn block, another validator will take its place proposing an off-turn block, slashing the missing validator. This is a security measure that should never be skipped.

#### Actual behaviour

Validators running puissant are skipping off turn block proposals. Currently puissant is being run by 6 cabinet validators out of 21 (almost 30% of validators).

I think that there are some rules that must be followed in order to ensure the correct working of BSC. Slashing mechanism are at least one of the few measures that should be followed by all validators. The following table shows the number of slashes done by each validator since January, the only missing validators are puissant validators. Some validators have low slash count since they recently joined the chain or the went offline/jailed in the observation time.

| *Slasher* | *Slash Count*                 |
|--------------------------------------------|---------------------------------|
| LegendIV                                   | 11
| Hallasan                                   | 3                               |
| Syn                                        | 48                              |
| NodeReal                                   | 60                              |
| Ankr                                       | 42                              |
| Defibit                                    | 209                             |
| Legend III                                 | 87                              |
| Sky                                        | 21                              |
| Certik                                     | 148                             |
| PexMons                                    | 37                              |
| Saturn                                     | 157                             |
| Tranchess                                  | 130                             |
| NameLix                                    | 47                              |
| BitStack                                   | 12                              |
| Aoraki                                     | 7                               |
| BscScan                                    | 48                              |
| HashQuark                                  | 178                             |
| Legend                                     | 52                              |
| Legend II                                  | 76                              |
| InfStones                                  | 142                             |
| TW Staking                                 | 61                              |
| LegendV                                    | 13                              |
| Blockorus                                  | 1                               |
| Figment                                    | 141                             |
| MathWallet                                 | 130                             |
| BisonTrails                                | 15                              |
| Fuji                                       | 95                              |

#### Steps to reproduce the behaviour

Wait for a validator to miss/delay its block production. Some validators will propose off turn blocks. Puissant validators wont.

#### Backtrace
Cant reproduce
````
[backtrace]
````
No backtrace
When submitting logs: please submit them as text and not screenshots.

**Comment by Ezkerrox** [comment]
Yes, does no seem to make sense. I just wanted to raise this issue because as more validators might join them, it might get to a point in which this is a problem?

**Comment by Undead8** [comment]
They do this because it is an important privacy protection. Since they receive private transactions that are not meant to go to the mempool until they are validated, they cannot propose off turn blocks. If they did, the private transaction would become public in the signed off turn block, yet this block may likely not be canonical. Someone could then use these private-now-public transactions for nefarious purposes and reuse them in another block.

**Comment by Undead8** [comment]
There are no rules besides those that are implemented in code and enforced through slashing. Since becoming a validator does not require permission or doxxing, any "consensus rules" outside those are not enforceable and therefore meaningless.

Validators can set minimum gas price as they see fit and they can decide to include transactions or not in a block and in any order they wish. 

Are you suggesting that validators should be slashed if they do not produce off turn blocks? Or that off turn blocks should give more incentives/reward so that validators choose to sign them?

**Comment by zzzckck** [comment]
Seems like Puissant has fixed this issue, it will produce non-mev block in off turn.
