### ISSUE TITLE
Nonce too high err

### ISSUE THREAD

**Issue by artjoma** [bnb-chain/bsc#1598]
#### System information

Geth version: `v1.2.1`
OS & Version: Linux

#### Actual behaviour
Err when calling traceBlockByNumber

#### Steps to reproduce the behaviour
Request: `{"method":"debug_traceBlockByNumber","params":["0x753C9"],"id":1,"jsonrpc":"2.0"}`
Response: `{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"nonce too high: address 0x70c25bc57Ba1F582075893D50De804d407FE68ea, tx: 261 state: 0"}}`

**Comment by ZiyuanStar** [comment]
you can try it with a different endpoint, this works for me:
curl https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3 \
-X POST \
-H "Content-Type: application/json" \
--data '{"method":"debug_traceBlockByNumber","params":["0x753C9", {"tracer": "callTracer"}],"id":1,"jsonrpc":"2.0"}'

**Comment by artjoma** [comment]
@ZiyuanStar thank you for your suggestion, but I want to use my own node.

**Comment by alexlucaci** [comment]
Hi @artjoma,

Is the node that you are executing the query against a non-archive one?
It seems like this issue was already reported by other users who were using non-archive nodes and trying to query blocks that are too far in the past (in your case your are looking for block 480k and bsc mainnet is at 28kk).
A non-archive node does not have all state of the data and thus can't process these requests so you need to use an archive node for these types of queries.

Please let me know if this is also your case :)

**Comment by artjoma** [comment]
This issue related to trace reexec=128.
```
statedb, err := api.backend.StateAtBlock(ctx, parent, reexec, nil, true, false)
```

Should return error if state unavailable (block_n + 128 < current block). 

Erigon provide method for state availability: [checkPruneHistory](https://github.com/ledgerwatch/erigon/blob/1106475e345d936aa1220ace3e95d746ec361fa4/cmd/rpcdaemon/commands/eth_api.go#L272)

@alexlucaci Could you please advice.

**Comment by alexlucaci** [comment]
I don't understand what you are asking for. Also, can you please respond to my question? Is your node an archive one?

**Comment by artjoma** [comment]
@alexlucaci non-archive node, fully synchronized.
