### ISSUE TITLE
Is it possible to purchase an archive snapshot data?

### ISSUE THREAD

**Issue by harveyff** [bnb-chain/bsc#1622]
Hi everyone,

We need to run a geth archive node of our own. As you know, the data size is now nearly 46T. I think the synchronization from the genesis node will never be completed.

I'd like to buy a geth archive node snapshot if possible, and would be grateful if any of the guys had helpful advice.

In addition, we have tried erigon's archive, but it doesn't understand, and it always lags behind too fast. Not stable enough to be used in a production environment.

The third-party rpc provider has also been considered, but it is not flexible enough, so we always want to have our own geth archive node.

best wishes.

**Comment by brilliant-lx** [comment]
Sorry, it is too large to maintain a snapshot of 46TB, so we do not support it.

> In addition, we have tried erigon's archive, but it doesn't understand, and it always lags behind too fast. Not stable enough to be used in a production environment.
BSC archive will be supported by Erigon, it does have some issues, like lagging behind, but someone is already investigating on it. Hopefully, it could be solved soon.
I think Erigon BSC will gradually improve its UX, since it still at early stage, would take sometime for engineers to dive deep into the codebase and gather the experience.
