### ISSUE TITLE
what is state healing

### ISSUE THREAD

**Issue by cliff0412** [bnb-chain/bsc#1718]
i am a bsc node operator. occasionally there might be some logs like
```
Syncing, state heal in progress
```
can help explain what does this exactly mean?

also, what is the meaning of DirtyTrieCache and CleanTrieCache.

btw, what may be the best place to learn/discuss tech of bsc & geth? any tg group?

**Comment by weiihann** [comment]
State healing refers to the process of repairing and restoring the state database to resolve inconsistencies so that the state is consistent with the network. Generally, it should be normal to have this log unless it starts to disrupts syncing.

DirtyTrieCache is a cache that holds trie nodes that have been modified or created during the execution of transactions or contract interactions. It's called "dirty" because it may contain trie nodes that are not yet persisted to the underlying storage.

CleanTrieCache is a cache that holds trie nodes that have already been persisted to the underlying storage. It is called "clean" because it contains trie nodes that have been committed and are considered finalized.

Discussions on nodes are usually quite active on Discord. You may join BNB Chain discord using [this link](https://discord.com/invite/bnbchain).

In the `roles` channel, select **Node Operators**. Then you should see `node-support` channel. The discussion usually takes place there.

Hope it helps! :)

**Comment by cliff0412** [comment]
thanks for your explanation for dirty & clean trie cache. what may cause a state healing btw?

**Comment by weiihann** [comment]
Based on my understanding of that sentence, regenerated tries can be invalidated because of prolonged network connectivity issues. As new blocks are added, the regenerated state tries may become inconsistent or outdated. Therefore, state healing is needed to repair the state database as it catches up with the latest block. It could also be triggered due to other issues such as reorg.

**Comment by cliff0412** [comment]
i think the only situation might be due to reorg. otherwise the old regenerated tries should be correct. the client may choose not to keep the tries in memory (outdated); but it is still a validated trie.

**Comment by weiihann** [comment]
Not necessarily. Referring to the [Geth's docs](https://geth.ethereum.org/docs/fundamentals/logs).
> Meanwhile, the blockchain continues to progress and the target header is updated. This means some of the regenerated state data need to be updated. This is known as healing.

The header is verified, but the underlying state has yet to reflect the correct changes.

**Comment by cliff0412** [comment]
but the key word here is actually **regenerated state**. it means the state has already been generated according to leave nodes. if header is verified, the regenerated state can be verified also. why the regenerated state could possibly to invalidated

**Comment by weiihann** [comment]
The term "invalidated" may be misleading. Perhaps a more suitable term would be "outdated".

In other words, the regenerated state is "invalidated" because the state does not match the latest header, which means the state is outdated. Thus, healing is required so that the state matches the latest header.
