### ISSUE TITLE
VerifyNode - block ancestor has not been verified

### ISSUE THREAD

**Issue by 123wyl123** [bnb-chain/bsc#1836]
When I set up a verifynode and a fastnode (--tries-verify-mode = full) referring to this document(https://docs.bnbchain.org/docs/BSC-separate-node),fastnode only connects to my own deployment of verifynode. fastnode get this error (block ancestor has not been verified), should the verifynode be an archive node as a normal full node will only store 128 blocks of MPT.

**Comment by weiihann** [comment]
May I get the node startup command for both your verify node and fast node?

**Comment by 123wyl123** [comment]
@weiihann 
hello,thank  for the reply.
verifynodes 
./geth --config ./config.toml --datadir ./node --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0 --enabletrustprotocol --disablesnapprotocol --disablediffprotocol
fastnodes 
./geth --tries-verify-mode full --config ./config.toml --datadir ./node  --cache 8000 --rpc.allow-unprotected-txs --txlookuplimit 0

I'm using 48club's full node snapshot.

If you can't reproduce the issue fully, I was wondering if I can use the interfaces debug_trace, or eth_getTransactionReceipt when I use fastnodes like trials-verify-mode = full or non-local that don't store mpt state?As far as I know these interfaces are related to mpt , since I haven't fully started fastnode I can't verify my thoughts.
If I can use these interfaces by fastnode, is it because fastnode will query the corresponding mpt state from the verifynode to get the result? So will verifynode have more consumption than non-verifynode e.g. trials-verify-mode=local. looking forward to your reply!

**Comment by weiihann** [comment]
I checked the codes, I found that the relevant codes don't log them. So I'd assume that debug_trace or eth_getTransactionReceipt might not help much.

From the [docs](https://docs.bnbchain.org/docs/BSC-separate-node), a verifynode receives diff hash from fastnode, then verifynode will find the corresponding difflayer whose diffhash is matched and then send back the MPT state root to the fastnode.

Based on this logic, different scenarios could result in the error:
- fastnode's diffhash is invalid, that's why verifynode can't find the MPT state root hash
- fastnode's diffhash is valid, but verifynode doesn't have the MPT state root hash

Few additional questions to get more context:
- Is your verifynode fully synced?
- Can you show the partial logs where `block ancestor has not been verified` is encountered?
