### ISSUE TITLE
purpose of --prunceancient flag

### ISSUE THREAD

**Issue by zxsimba** [bnb-chain/bsc#1862]
What is the usages of A node with --prunceancient flag?
Could it be used to execute all transactions that a full node can?
What is the limitations of such a node?

**Comment by weiihann** [comment]
Do refer to this [doc](https://docs.bnbchain.org/docs/validator/node-maintenance#prune-ancient-data-in-real-time).

For a regular full node, it shouldn't be too much of a problem. It can execute transactions as normal since execution does not require ancient data. However, if a party were to request a specific block info that has been pruned, then it would result in an error.
