### ISSUE TITLE
v1.3.1 performance issue, stuck in 'Allocated cache and file handles' for about 4min after restart

### ISSUE THREAD

**Issue by irrun** [bnb-chain/bsc#1987]
#### System information

Geth version: `v1.3.1`
OS & Version: Linux
Commit hash: master (1dca486622ae46636b888fa10f8a8dbf0879e7e8)

#### Expected behaviour

spend less than 1min for 'Allocated cache and file handles' 

#### Actual behaviour
<img width="1249" alt="截屏2023-11-15 11 35 12" src="https://github.com/bnb-chain/bsc/assets/10414287/dcc58082-b240-411b-a4ef-b47a8293789d">

#### Steps to reproduce the behaviour

it's > 50% reproducible when conducting service bsc stop and start

#### Backtrace

````
t=2023-11-15T03:05:22+0000 lvl=info msg="Blockchain stopped"
t=2023-11-15T03:05:57+0000 lvl=warn msg="stop p2p server timeout, forcing stop"
t=2023-11-15T03:06:16+0000 lvl=info msg="Using leveldb as the backing database"
t=2023-11-15T03:06:16+0000 lvl=info msg="Allocated cache and file handles"      database=/server/validator/geth/chaindata cache="7.03 GiB" handles=250,000 readonly=true
t=2023-11-15T03:09:31+0000 lvl=info msg="Using LevelDB as the backing database"
t=2023-11-15T03:09:31+0000 lvl=info msg="Found legacy ancient chain path"       location=/server/validator/geth/chaindata/ancient
t=2023-11-15T03:09:31+0000 lvl=info msg="Opened ancient database"               database=/server/validator/geth/chaindata/ancient readonly=true frozen=33,413,094
t=2023-11-15T03:09:31+0000 lvl=info msg="State scheme set to already existing"  scheme=hash
t=2023-11-15T03:09:31+0000 lvl=warn msg="The flag --txlookuplimit is deprecated and will be removed, please use --history.transactions"
t=2023-11-15T03:09:31+0000 lvl=info msg="Set global gas cap"                    cap=50,000,000
t=2023-11-15T03:09:31+0000 lvl=info msg="Initializing the KZG library"          backend=gokzg
t=2023-11-15T03:09:32+0000 lvl=info msg="Allocated trie memory caches"          clean="2.64 GiB" dirty="4.39 GiB"
t=2023-11-15T03:09:32+0000 lvl=info msg="Using leveldb as the backing database"
t=2023-11-15T03:09:32+0000 lvl=info msg="Allocated cache and file handles"      database=/server/validator/geth/chaindata         cache="7.03 GiB" handles=250,000
t=2023-11-15T03:13:16+0000 lvl=info msg="Using LevelDB as the backing database"
t=2023-11-15T03:13:16+0000 lvl=info msg="Found legacy ancient chain path"       location=/server/validator/geth/chaindata/ancient
````
````
INFO [11-14|07:32:01.210] Maximum peer count                       ETH=900 LES=0 total=900
INFO [11-14|07:32:01.212] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [11-14|07:32:01.213] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
INFO [11-15|02:47:10.934] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [11-15|02:47:10.947] Starting Geth on Ethereum mainnet...
INFO [11-15|02:47:10.952] Maximum peer count                       ETH=900 LES=0 total=900
INFO [11-15|02:47:10.954] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [11-15|02:47:10.955] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
INFO [11-15|03:06:15.463] Starting pprof server                    addr=http://0.0.0.0:6060/debug/pprof
INFO [11-15|03:06:15.476] Starting Geth on Ethereum mainnet...
INFO [11-15|03:06:15.481] Maximum peer count                       ETH=900 LES=0 total=900
INFO [11-15|03:06:15.484] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
WARN [11-15|03:06:15.484] Option nousb is deprecated and USB is deactivated by default. Use --usb to enable
````

**Comment by RenRick** [comment]
It took a longer time to open LevelDB because LevelDB need to spend some time to recover database if it is not closed properly. 

From the log below we can see the blockchain was forced to shutdown when persisting data to database. And it took about 3~4 mins to recover database for LevelDB.

--- Log for the blockchain shutdown:
“t=2023-11-15T03:05:21+0000 lvl=info msg="Persisted trie from memory database"   nodes=2860    size="1.13 MiB"   time=25.8076ms    gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=80392 livesize="32.04 MiB"
t=2023-11-15T03:05:21+0000 lvl=info msg="Writing cached state to disk"          block=33,502,974 hash=0x574b5cc1328d1f4a31ce0b0e9ec4eba64327de4a7319f69506b78ce82c288c33 root=0x7b9f3f19b305ec08a5d6c5ac1407ea1f333e9a0f3feac0fbef6bcd45ad905dcf
t=2023-11-15T03:05:21+0000 lvl=info msg="Persisted trie from memory database"   nodes=0       size="0.00 B"     time="2.429µs"    gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=80392 livesize="32.04 MiB"
t=2023-11-15T03:05:21+0000 lvl=info msg="Writing snapshot state to disk"        root=0xbf198f23fa58c39fd9fd62a40cb75fcc30b4486cab63859f416f53924def226e
t=2023-11-15T03:05:21+0000 lvl=info msg="Persisted trie from memory database"   nodes=0       size="0.00 B"     time="1.206µs"    gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=80392 livesize="32.04 MiB"
t=2023-11-15T03:05:21+0000 lvl=info msg="Writing snapshot state to disk"        root=0xbf198f23fa58c39fd9fd62a40cb75fcc30b4486cab63859f416f53924def226e
t=2023-11-15T03:05:21+0000 lvl=info msg="Persisted trie from memory database"   nodes=0       size="0.00 B"     time=919ns        gcnodes=0       gcsize="0.00 B"     gctime=0s           livenodes=80392 livesize="32.04 MiB"
t=2023-11-15T03:05:22+0000 lvl=info msg="Blockchain stopped"
t=2023-11-15T03:05:57+0000 lvl=warn msg="stop p2p server timeout, forcing stop"
”

--- Restart, LevelDB spent about 4 mins to recover. 
"
t=2023-11-15T03:09:32+0000 lvl=info msg="Allocated cache and file handles"      database=/server/validator/geth/chaindata         cache="7.03 GiB" handles=250,000
t=2023-11-15T03:13:16+0000 lvl=info msg="Using LevelDB as the backing database"
"

**Comment by RenRick** [comment]
It was normal behavior. And it is recommended to stop the service properly.

**Comment by irrun** [comment]
got it, thanks
