### ISSUE TITLE
CPU Usage too high 

### ISSUE THREAD

**Issue by alexexxman** [bnb-chain/bsc#1992]
It is suspected that when the number of block transactions is too large (more than 2000), the rpc request will be very slow. And the node server CPU usage too high, what can I do to deal this question

**Comment by alexexxman** [comment]
the block of large txs have a large of tx like below, is garbage tx?
<img width="1382" alt="image" src="https://github.com/bnb-chain/bsc/assets/126240164/63121e46-afdc-4a71-9181-b0a54d9017f4">

**Comment by CocoStarZ** [comment]
What's your geth version?

**Comment by alexexxman** [comment]
V1.2.13 . Research findings，Due to the large volume of block transactions, the number of RPC requests has skyrocketed, so the CPU is full. Do you know the maximum number of rpc requests per second?

**Comment by weiihann** [comment]
AFAIK we don't have a benchmarked maximum number of RPC requests per second. If you want to minimize redundant CPU resources, I'd suggest reducing the `MaxPeer` number in the configuration file and resyncing again.

Also, it seems like this is more of an application problem rather than a problem with BSC itself. Do seek out other potential solutions such as throttling, etc.
