### ISSUE TITLE
v1.3.7 upgrade from v1.2.13 does not work

### ISSUE THREAD

**Issue by dandavid3000** [bnb-chain/bsc#2174]
#### System information

Geth version: Upgrade to v1.3.7 from v1.2.13
OS & Version:Linux

#### Expected behaviour
Light node works correctly after the upgrade

#### Actual behaviour

Asking for some flags and configs are missing:

#### Steps to reproduce the behaviour
Download geth_linux version v1.3.7 and replace v1.2.13 to run.

#### Backtrace

```
./run_bsc_light.sh 
INFO [01-20|00:52:55.690] Starting Geth on BSC mainnet... 
INFO [01-20|00:52:55.690] Bumping default cache on mainnet         provided=1024 updated=4096
Fatal: ./config.toml, line 6: field 'UltraLightFraction' is not defined in ethconfig.Config, see https://godoc.org/github.com/ethereum/go-ethereum/eth/ethconfig#Config for available fields

./run_bsc_light.sh 
INFO [01-20|00:56:39.986] Starting Geth on BSC mainnet... 
INFO [01-20|00:56:39.986] Bumping default cache on mainnet         provided=1024 updated=4096
WARN [01-20|00:56:39.987] Config field is deprecated and won't have an effect name=ethconfig.Config.EWASMInterpreter
WARN [01-20|00:56:39.987] Config field is deprecated and won't have an effect name=ethconfig.Config.EVMInterpreter
Fatal: ./config.toml, line 17: field 'Noverify' is not defined in miner.Config, see https://godoc.org/github.com/ethereum/go-ethereum/miner#Config for available fields
```

Could you please help me to upgrade my light node? Please find below the bash I use to run my node

`./geth_linux --config ./config.toml  --http --ws --datadir /bsc/geth.fast/geth --txlookuplimit=0 --syncmode=full --tries-verify-mode=none --pruneancient=true  --rpc.txfeecap 0`

**Comment by zzzckck** [comment]
1.UltraLightFraction & Noverify are not supported since [v1.3.0](https://github.com/bnb-chain/bsc/releases/tag/v1.3.0), just remove it from your config.toml
<img width="1071" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/04369a35-fb72-48c9-b050-f5f3b0218a81">
2.`--txlookuplimit 0` has been replaced by `--history.transactions 0`
<img width="906" alt="image" src="https://github.com/bnb-chain/bsc/assets/152148891/3fd990f1-8aa8-46f0-8c30-463991d3afe1">
3.Light Node is no longer supported, refer: https://github.com/bnb-chain/bsc/issues/2162
