### ISSUE TITLE
Node stop syncing since 2 days ago. Pull the latest v1.3.8. Still can't sync

### ISSUE THREAD

**Issue by nakedkoalacapital** [bnb-chain/bsc#2182]
I was running a local fork of the bsc node. (I forked around August 2023). It was syncing fine until 2 days ago.

I saw a lot of 

```
ARN [01-25|16:20:36.244] Snapshot extension registration failed   peer=172b7561 err="peer connected on snap without compatibl without compatible eth support"WARN [01-25|16:21:35.052] Snapshot extension registration failed   peer=bfd22e9c err="peer connected on snap without compatibl without compatible eth support"WARN [01-25|16:21:46.125] Snapshot extension registration failed   peer=2397eced err="peer connected on snap without compatibl without compatible eth support"WARN [01-25|16:21:46.640] Snapshot ex
```

I have pulled the latest change. Now I am at v.1.3.8 (commit c6aeee20016181a5ad4153acbbbf2cf1b27be0a5)

But the node still won't sync. 

Same error as above.

I have deleted data_dir/nodekey as other post suggested. But that didn't help.

**Comment by deepcrazy** [comment]
Hi there, What's your geth startup command? And please share more logs by setting log level to debug.

Couple of tips:
- Make sure to update the config.toml as per the latest release (https://github.com/bnb-chain/bsc/releases/tag/v1.3.7)
- Refer to this blog: https://www.bnbchain.org/en/blog/hotfix-hardfork-for-bsc-testnet-and-mainnet (as since v1.3.x, this flag: `--history.transactions 0` has to be used instead of `--txlookuplimit 0`
-  Also, If using path base state scheme, then please add these flags: `--db.engine=pebble --state.scheme=path` and refer this blog: https://forum.bnbchain.org/t/faq-pbss-pebbledb/2260#q3-how-to-try-pbss-pebbledb-7 and docs: https://docs.bnbchain.org/docs/validator/fullnode/

**Comment by zzzckck** [comment]
would you also remove this foldler and retry: "\<datadir\>/geth/nodes"
the log of "Snapshot extension registration failed" did not give any useful message, I still wonder if you have connected to other peers.
