### ISSUE TITLE
erorr="retrieved hash chain is invalid: blob info mismatch: sidecars 0, versionedHashes:1"

### ISSUE THREAD

**Issue by zzzckck** [bnb-chain/bsc#2540]
#### System information

Geth version: v1.4.10
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour
on restart, no error logs

#### Steps to reproduce the behaviour
1.stop the node for a while, then restart, the node can sync but will have many error log:
```
t=2024-06-25T14:43:56+0000 lvl=warn msg="Synchronisation failed, dropping peer" peer=16f64d7954810c73078e0c02e713f136b38169bee989e405a7995b03fda11fb1 err="retrieved hash chain is invalid: blob info mismatch: sidecars 0, versionedHashes:1"
```

#### Backtrace
NA

**Comment by galaio** [comment]
For nodes using >= v1.4.8, the message of the actual blob will not be forwarded further, it checks in here. https://github.com/bnb-chain/bsc/blob/75d162983a209b438f61adbb0e71e79d71a21ec7/eth/handler.go#L330

In the tracking in the past two weeks, it was found that many unknown commit versions were broadcasting wrong blocks (blobs mismatch), and some known service providers have been repaired.
```bash
Geth/v1.4.10-a9e80f8a-20240624/linux-arm64/go1.21.9
Geth/v1.4.9-24d48ffa/linux-arm64/go1.21.9
Geth/v1.4.8/linux-amd64/go1.22.3
```

The current blobs mismatch frequency is pretty low, but it still needs to be tracked. The last suggestion is that if you use a release version other than BSC Repo, please migrate to the official release, otherwise please check whether there is a problem of forwarding lost blobs.
https://github.com/bnb-chain/bsc/releases/tag/v1.4.11
