### ISSUE TITLE
LevelDB compaction throttle for faster SYNC?

### ISSUE THREAD

**Issue by slawomir-pryczek** [bnb-chain/bsc#574]
# Rationale

Sync is getting very slow recently, i noticed that at least on my system it is related to I/O and LevelDB compaction. Maybe it'll be possible to add a new switch --compaction_throttle=X where X will be number of seconds to wait after single compaction task is finished (Lx -> Lx+1). This should lower disk utilization.

# Implementation

Can try to implement this feature when I have some time if you think this could help. Shouldn't be complicated.

**Comment by RenRick** [comment]
Sync speed is based on the reading performance. And LevelDB compaction commonly occupy less than 100MB/s disk bandwidth. Reading performance will be impacted heavily If disk bandwidth is run out of use. But if disk bandwidth is enough, there should be no obvious change to reading performance. And also as we know compaction is helpful to sort data in order to get better reading performance.  I am afraid it will not help to sync speed when there are a large amount of transaction handling. Actually I prefer to async reading or execution in parallel, which could make full use of disk bandwidth, to get better throughput.
