### ISSUE TITLE
Avengers keeps mining two blocks every round

### ISSUE THREAD

**Issue by Ezkerrox** [bnb-chain/bsc#765]
Hey, 
First of all I am not sure if this is the place to open an issue about this, but I cant think of any other place to post it.

It happens that **almost every** time is the turn of the validator "Avengers" to mine a block, it keeps mining 2 valid blocks instead of 1. This issue has been happening for the past few days. I dont know how it could affect this fact to the well-functioning of the blockchain, but I think they should attach this issue as soon as possible.

Both blocks seem to be valid, the only difference is the amount of transactions and the order of the transactions inside the block. I am attaching an screenshot of some of the blocks that are being mined by Avengers.
![a](https://user-images.githubusercontent.com/55693023/153845586-7c2699c0-666b-4d1d-a5eb-5bfb1b46caf4.jpeg)

Other validator ocasionally send duplicated blocks, for this sample of ~1725 blocks per validator, Avengers mined 3533 from which 1720 were duplicated, while the next validator with more duplicated blocks is HashQuark with only 2 duplicated blocks out of 1735.

**Comment by Zaczero** [comment]
### My theory
They run 2 servers in parallel to ensure high uptime in case one of the servers goes offline/lags behind. On each server, they run a validator node that keeps producing blocks per schedule. Because of slight differences in terms of server location and network latency, each of the produced blocks is different (different hash, different amount of tx).

All of that is completely fine as only one of the blocks gets included in the blockchain anyway (there can't be 2 blocks with the same number, and they cannot produce 2 subsequent blocks, with different numbers, as per BSC protocol).

Quick link to bscscan and related blocks:
https://bscscan.com/block/15245758 - Ankr
https://bscscan.com/block/15245759 - **Avengers**
https://bscscan.com/block/15245760 - Anonymous

**Comment by 48ClubSirIan** [comment]
Hi, I've reached Avengers operator and this turns out to be an operating accident.

1. Internal monitoring link broken.
2. Backup node turns on for take over.
3. Both keep online 'cause they both consider themselves as the only active one.

It should be fine since 3 hours ago.

**Comment by Ezkerrox** [comment]
Hey, thanks for letting them know :). It looks like its working properly right now. 
Double signing is a big risk for all validators, so I guess they need to take more care about this issue. It was obvious they were having some issue, so we decided to post here rather than slashing.
Anyway, I think all validators should take more care about double signing, penalties are quite high...
