### ISSUE TITLE
peerCount recommendations

### ISSUE THREAD

**Issue by Marijus** [bnb-chain/bsc#988]
I'm successfully running full node with mgasps way above the recommended 50. However, my peer count is only 26-30.

I've set my MaxPeers = 100 and updated static nodes with nodes from here: https://api.binance.org/v1/discovery/peers

However, it has not increased from the initial 30. 

1. How do I increase the number of peers?
2. What effect will the number of peers will have?

**Comment by psdlt** [comment]
hi. to increase your peer count you first need to open up `ListenAddr` (30311 by default) for incoming connections, otherwise you will only get 1/3 of your `MaxPeers`.
what effect will higher number have? higher bandwidth usage, higher cpu usage, maybe your node will learn about new blocks and txs faster.
